import { Brand } from '../../../types/brand';

export const brandScenarioA: Omit<Brand, 'id' | 'userId' | 'createdAt' | 'updatedAt'> = {
  name: '달달한 발견',
  tagline: '하루 한 조각, 달콤한 영감',
  slogan: '당신의 일상에 디저트 한 조각을',
  story: '바쁜 일상 속에서도 작은 달콤함을 놓치고 싶지 않은 사람들을 위해 태어났습니다. 매일 하나의 특별한 디저트를 발견하고, 그 안에 담긴 이야기를 전합니다. 우리는 디저트가 단순한 간식이 아니라, 하루를 견디게 해주는 작은 행복이라고 믿습니다.',
  targetCustomer: '25~35세 직장인 여성. 퇴근 후 작은 행복을 찾는 사람. 인스타그램에서 예쁜 카페와 디저트를 저장하는 습관이 있는 사람.',
  toneAndManner: '따뜻하고 감성적이면서도 정보가 있는 톤. 친구에게 맛집을 추천하듯 편안하게, 하지만 전문적인 디테일도 놓치지 않는 스타일.',
  colorPalette: {
    primary: '#F4A261',
    secondary: '#2A9D8F',
    accent: '#E76F51',
    background: '#FEFAE0',
    text: '#264653',
  },
  logoConcept: '미니멀한 케이크 아이콘과 손글씨 느낌의 브랜드명 조합. 따뜻한 오렌지 톤으로 달콤함을 표현.',
  snsProfile: {
    bio: '🍰 하루 한 조각, 달콤한 영감\n매일 발견하는 특별한 디저트 이야기\n📍 서울 디저트 큐레이터',
    platforms: [
      { platform: 'instagram', username: '@daldalhan_discovery', bio: '하루 한 조각, 달콤한 영감 🍰' },
      { platform: 'blog', username: 'daldalhan-discovery', bio: '디저트로 시작하는 작은 행복' },
    ],
  },
  firstContentIdeas: [
    {
      title: '퇴근 후 5분 거리, 오늘의 디저트 추천',
      platform: 'Instagram',
      format: '카드뉴스 (5장)',
      hook: '"오늘 하루 고생했으니까, 이 한 조각은 괜찮아"',
      description: '직장인 밀집 지역 근처 숨은 디저트 맛집 소개. 가격, 위치, 추천 메뉴를 한눈에.',
    },
    {
      title: '이번 주 서울 디저트 트렌드 TOP 3',
      platform: 'Blog',
      format: '리뷰 포스트',
      hook: '이번 주 인스타에서 가장 많이 저장된 디저트는?',
      description: '주간 트렌드 디저트를 직접 방문 후 리뷰. 사진 + 맛 평가 + 가성비 분석.',
    },
    {
      title: '집에서 5분 만에 만드는 카페 디저트',
      platform: 'Instagram',
      format: '릴스 (30초)',
      hook: '카페 안 가도 됩니다. 진짜로.',
      description: '간단한 홈디저트 레시피 숏폼. 재료 3개 이하, 시간 5분 이내.',
    },
  ],
  revenueModel: {
    primary: '인스타그램 협찬 & 브랜드 콜라보',
    secondary: '디저트 큐레이션 뉴스레터 유료 구독',
    timeline: '4주 후 첫 수익 발생 가능',
    estimatedMonthly: '50~150만원',
    steps: [
      '인스타그램 1,000 팔로워 달성 (2주)',
      '디저트 카페 3곳 무료 협찬 제안 (3주)',
      '첫 유료 협찬 콘텐츠 제작 (4주)',
      '월 4회 브랜드 콜라보 콘텐츠 안정화 (8주)',
    ],
    risks: ['콘텐츠 소재 고갈 가능성', '계절별 트렌드 변화에 민감'],
  },
  actionPlan30: [
    { day: 1, title: '인스타그램 계정 생성 & 프로필 세팅', description: '브랜드 컬러, 프로필 사진, 바이오 설정', category: 'setup', estimatedMinutes: 30, completed: false },
    { day: 2, title: '브랜드 무드보드 제작', description: 'Pinterest에서 레퍼런스 수집, 컬러 팔레트 확정', category: 'setup', estimatedMinutes: 45, completed: false },
    { day: 3, title: '첫 디저트 방문 & 촬영', description: '근처 디저트 카페 방문, 사진 10장 이상 촬영', category: 'content', estimatedMinutes: 60, completed: false },
    { day: 4, title: '첫 포스트 업로드', description: '카드뉴스 형태로 첫 디저트 리뷰 포스팅', category: 'content', estimatedMinutes: 40, completed: false },
    { day: 5, title: '해시태그 전략 수립', description: '디저트 관련 해시태그 30개 리서치 & 저장', category: 'growth', estimatedMinutes: 20, completed: false },
    { day: 6, title: '릴스 콘텐츠 촬영', description: '홈디저트 레시피 숏폼 1개 촬영', category: 'content', estimatedMinutes: 45, completed: false },
    { day: 7, title: '1주차 리뷰 & 다음 주 계획', description: '팔로워 수, 좋아요, 저장 수 체크', category: 'growth', estimatedMinutes: 15, completed: false },
    { day: 8, title: '경쟁 계정 분석', description: '디저트 인플루언서 5명 콘텐츠 스타일 분석', category: 'growth', estimatedMinutes: 30, completed: false },
    { day: 9, title: '블로그 개설', description: '네이버 블로그 또는 티스토리 개설, 프로필 세팅', category: 'setup', estimatedMinutes: 30, completed: false },
    { day: 10, title: '블로그 첫 포스트', description: '상세 디저트 리뷰 (사진 + 맛 + 가격 + 위치)', category: 'content', estimatedMinutes: 60, completed: false },
    { day: 11, title: '인스타 스토리 루틴 시작', description: '매일 1개 이상 디저트 관련 스토리 업로드', category: 'content', estimatedMinutes: 15, completed: false },
    { day: 12, title: '팔로워 소통 시작', description: 'DM 답장, 댓글 소통, 투표 스토리 활용', category: 'growth', estimatedMinutes: 20, completed: false },
    { day: 13, title: '콘텐츠 배치 제작', description: '주말 활용하여 3~5개 콘텐츠 미리 제작', category: 'content', estimatedMinutes: 90, completed: false },
    { day: 14, title: '2주차 리뷰', description: '성장 지표 분석, 가장 반응 좋은 콘텐츠 유형 파악', category: 'growth', estimatedMinutes: 20, completed: false },
    { day: 15, title: '콜라보 제안서 작성', description: '디저트 카페 협찬 제안 템플릿 작성', category: 'revenue', estimatedMinutes: 45, completed: false },
    { day: 16, title: '카페 3곳 DM 발송', description: '무료 협찬 제안 DM 발송', category: 'revenue', estimatedMinutes: 30, completed: false },
    { day: 17, title: '시즌 콘텐츠 기획', description: '다음 달 시즌 디저트 콘텐츠 3개 기획', category: 'content', estimatedMinutes: 30, completed: false },
    { day: 18, title: '릴스 2개 촬영', description: '트렌드 오디오 활용 디저트 릴스', category: 'content', estimatedMinutes: 60, completed: false },
    { day: 19, title: '뉴스레터 플랫폼 조사', description: '스티비, 메일침프 등 비교 분석', category: 'setup', estimatedMinutes: 30, completed: false },
    { day: 20, title: '뉴스레터 0호 작성', description: '테스트 뉴스레터 작성 (주간 디저트 추천)', category: 'content', estimatedMinutes: 45, completed: false },
    { day: 21, title: '3주차 리뷰', description: '전환점 분석, 전략 수정 필요 여부 판단', category: 'growth', estimatedMinutes: 20, completed: false },
    { day: 22, title: '협찬 콘텐츠 촬영', description: '협찬 제안 수락된 카페 방문 & 촬영', category: 'revenue', estimatedMinutes: 90, completed: false },
    { day: 23, title: '협찬 콘텐츠 업로드', description: '협찬 표기 포함 포스팅', category: 'revenue', estimatedMinutes: 40, completed: false },
    { day: 24, title: '팔로워 1,000명 달성 캠페인', description: '이벤트 또는 콜라보를 통한 팔로워 확보', category: 'growth', estimatedMinutes: 30, completed: false },
    { day: 25, title: '콘텐츠 캘린더 수립', description: '다음 달 주간 콘텐츠 계획표 작성', category: 'setup', estimatedMinutes: 30, completed: false },
    { day: 26, title: '유료 협찬 견적 작성', description: '협찬 단가표 초안 작성', category: 'revenue', estimatedMinutes: 30, completed: false },
    { day: 27, title: '포트폴리오 정리', description: '지금까지 콘텐츠 중 베스트 선정, 미디어킷 제작', category: 'revenue', estimatedMinutes: 45, completed: false },
    { day: 28, title: '2곳 추가 협찬 제안', description: '유료 협찬 제안 발송', category: 'revenue', estimatedMinutes: 30, completed: false },
    { day: 29, title: '커뮤니티 확장', description: '디저트 관련 오픈채팅, 커뮤니티 참여', category: 'growth', estimatedMinutes: 20, completed: false },
    { day: 30, title: '30일 회고 & 다음 목표 설정', description: '전체 성과 정리, 60일 목표 수립', category: 'growth', estimatedMinutes: 30, completed: false },
  ],
  status: 'active',
};
