import { BrandRecommendation } from '../../../types/brand';

export const scenarioA: BrandRecommendation[] = [
  {
    id: 'rec-a1',
    title: '디저트 큐레이션 브랜드',
    description: '숨은 디저트 맛집을 발굴하고, 나만의 시선으로 큐레이션하는 콘텐츠 브랜드. 인스타그램과 블로그를 중심으로 디저트 리뷰와 감성 사진을 공유합니다.',
    category: '푸드/라이프스타일',
    matchScore: 94,
    estimatedRevenue: '월 50~150만원',
    difficulty: 'easy',
    timeToFirstRevenue: '3~4주',
    whyFit: '음식과 디저트에 대한 높은 관심도, 감각적인 취향, 그리고 주 10시간 이상 투자 가능한 시간이 이 브랜드에 최적입니다.',
  },
  {
    id: 'rec-a2',
    title: '홈카페 레시피 브랜드',
    description: '집에서 카페 퀄리티의 음료와 디저트를 만드는 레시피를 공유하는 콘텐츠 브랜드. 숏폼 영상과 레시피 카드를 핵심 콘텐츠로 활용합니다.',
    category: '푸드/교육',
    matchScore: 88,
    estimatedRevenue: '월 80~200만원',
    difficulty: 'medium',
    timeToFirstRevenue: '4~6주',
    whyFit: '요리에 대한 관심과 창작 능력을 결합하면, 레시피 콘텐츠로 빠르게 팔로워를 확보할 수 있습니다.',
  },
  {
    id: 'rec-a3',
    title: '미식 뉴스레터 브랜드',
    description: '매주 한 번, 이번 주에 가봐야 할 맛집과 푸드 트렌드를 정리해 보내는 뉴스레터 기반 브랜드. 구독자 기반 수익 모델입니다.',
    category: '푸드/미디어',
    matchScore: 82,
    estimatedRevenue: '월 100~300만원',
    difficulty: 'medium',
    timeToFirstRevenue: '6~8주',
    whyFit: '글쓰기 능력과 푸드 지식을 결합하여, 충성도 높은 구독자 기반을 만들 수 있습니다.',
  },
];

export const scenarioB: BrandRecommendation[] = [
  {
    id: 'rec-b1',
    title: '생산성 도구 큐레이션 브랜드',
    description: 'AI 시대의 새로운 생산성 습관과 도구를 소개하는 콘텐츠 브랜드. 노션 템플릿, 생산성 가이드, AI 활용법을 핵심 콘텐츠로 활용합니다.',
    category: '테크/생산성',
    matchScore: 96,
    estimatedRevenue: '월 100~300만원',
    difficulty: 'easy',
    timeToFirstRevenue: '2~4주',
    whyFit: 'AI와 생산성 도구에 대한 깊은 이해, 체계적인 성격이 이 분야에서 강력한 경쟁력이 됩니다.',
  },
  {
    id: 'rec-b2',
    title: 'AI 활용 가이드 브랜드',
    description: '비전문가도 쉽게 따라할 수 있는 AI 활용법을 소개하는 교육 브랜드. 온라인 강의와 전자책을 통해 수익을 창출합니다.',
    category: '교육/테크',
    matchScore: 91,
    estimatedRevenue: '월 150~500만원',
    difficulty: 'medium',
    timeToFirstRevenue: '4~6주',
    whyFit: 'AI에 대한 전문 지식과 설명 능력이 결합되면, 교육 콘텐츠에서 높은 수익을 기대할 수 있습니다.',
  },
  {
    id: 'rec-b3',
    title: '디지털 노마드 워크플로우 브랜드',
    description: '어디서든 효율적으로 일하는 방법을 공유하는 라이프스타일+생산성 브랜드. 블로그와 유튜브를 중심으로 운영합니다.',
    category: '라이프스타일/생산성',
    matchScore: 85,
    estimatedRevenue: '월 80~250만원',
    difficulty: 'medium',
    timeToFirstRevenue: '4~8주',
    whyFit: '테크 친화적인 성향과 자유로운 라이프스타일에 대한 관심이 이 브랜드의 핵심 동력이 됩니다.',
  },
];

export const scenarioC: BrandRecommendation[] = [
  {
    id: 'rec-c1',
    title: '느린 여행 기록 브랜드',
    description: '빠른 세상에서 천천히 여행하는 법을 공유하는 콘텐츠 브랜드. 감성 사진, 여행 에세이, 로컬 추천을 핵심으로 합니다.',
    category: '여행/라이프스타일',
    matchScore: 93,
    estimatedRevenue: '월 80~200만원',
    difficulty: 'easy',
    timeToFirstRevenue: '4~6주',
    whyFit: '여행에 대한 열정과 감성적 글쓰기 능력이 이 브랜드의 핵심 자산입니다.',
  },
  {
    id: 'rec-c2',
    title: '로컬 가이드 전자책 브랜드',
    description: '특정 지역의 숨은 명소, 맛집, 활동을 정리한 전자책 가이드를 판매하는 브랜드. 스마트스토어와 자체 웹사이트를 통해 판매합니다.',
    category: '여행/출판',
    matchScore: 87,
    estimatedRevenue: '월 100~400만원',
    difficulty: 'medium',
    timeToFirstRevenue: '6~8주',
    whyFit: '깊이 있는 여행 경험과 정보 정리 능력으로, 차별화된 여행 가이드를 만들 수 있습니다.',
  },
  {
    id: 'rec-c3',
    title: '여행 감성 굿즈 브랜드',
    description: '여행 영감을 담은 엽서, 스티커, 다이어리 등 감성 굿즈를 제작하고 판매하는 브랜드. 온라인 스토어를 중심으로 운영합니다.',
    category: '여행/커머스',
    matchScore: 79,
    estimatedRevenue: '월 50~150만원',
    difficulty: 'hard',
    timeToFirstRevenue: '8~12주',
    whyFit: '여행에서 받은 영감을 시각적으로 표현하는 능력이 있다면, 감성 굿즈 시장에서 차별화가 가능합니다.',
  },
];
